# Generated by Django 3.1.14 on 2023-06-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20221018_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='baseconfig',
            options={'verbose_name_plural': 'base config'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'income'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name_plural': 'period'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'user settings'},
        ),
        migrations.AlterField(
            model_name='baseconfig',
            name='country',
            field=models.CharField(choices=[('South Africa', 'South Africa'), ('United Kingdom', 'United Kingdom')], default='United Kingdom', max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.income'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
    ]
