# Generated by Django 3.1.14 on 2022-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20221017_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
