# Generated by Django 3.1.14 on 2022-10-17 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_baseconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='income_month',
        ),
        migrations.AddField(
            model_name='income',
            name='income_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
