# Generated by Django 3.1.14 on 2022-10-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20221017_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('utility', 'Utilities'), ('food', 'Groceries'), ('mobile', 'mobile'), ('subscription', 'Subscriptions'), ('other', 'Other')], default='Home', max_length=20),
        ),
    ]
